apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-frontend
  template:
    metadata:
      labels:
        name: pod-frontend
      name: frontend
    spec:
      containers:
      - image: ertis/kafka-ml-frontend:v1.5  # If you want to use our builded image at Docker Hub.
    # - image: localhost:5000/frontend       # If you want to use your local build image.
        name: frontend
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          - name: BACKEND_URL
            value: http://localhost:8000