apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: kafkaml
  name: kafkaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafkaml
  namespace: kafkaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafkaml-role
  namespace: kafkaml
rules:
- apiGroups:
  - ""
  - apps
  - batch
  resources:
  - deployments
  - jobs
  - pods
  - replicasets
  - services
  - replicationcontrollers
  verbs:
  - create
  - get
  - list
  - delete
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafkaml-rolebinding
  namespace: kafkaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafkaml-role
subjects:
- kind: ServiceAccount
  name: kafkaml
  namespace: kafkaml
---
apiVersion: v1
data:
  backend.address: backend:8000
  backend.allowedhosts: 127.0.0.1,localhost,backend
  backend.url: http://backend:8000
  brokers: kafka:9092
  control.topic: KAFKA_ML_CONTROL_TOPIC
  federated.modelloggertopic: FEDERATED_MODEL_CONTROL_TOPIC
  frontend.url: http://localhost
  pthexecutor.url: http://pthexecutor:8002/
  pytorch.inference.image: ertis/kafka-ml-pytorch_model_inference:v1.0@sha256:7fc6d731954419f7b122c67a560c4d1ed48499906d3444b530d59a18eab96c4a
  pytorch.training.image: ertis/kafka-ml-pytorch_model_training:v1.0@sha256:4bcfaa796c1301c8640406c19aeed56683e93f0e75835b6b30b9b5488ff350eb
  tensorflow.inference.image: ertis/kafka-ml-tensorflow_model_inference:v1.0@sha256:484b89e8a9980c4d56f4055692afde2a481e52b27fb1669ad2ad693f3a15fe28
  tensorflow.training.image: ertis/kafka-ml-tensorflow_model_training:v1.0@sha256:675544c4b72be6434906f8f0daae10688fd6808cc3b47474a7908a409af1e7a8
  tfexecutor.url: http://tfexecutor:8001/
kind: ConfigMap
metadata:
  name: kafkaml-configmap
  namespace: kafkaml
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kafkaml
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: pod-backend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kafkaml
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    name: pod-frontend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka
  name: kafka
  namespace: kafkaml
spec:
  ports:
  - name: "9094"
    port: 9094
    targetPort: 9094
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pthexecutor
  namespace: kafkaml
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    name: pod-pthexecutor
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tfexecutor
  namespace: kafkaml
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    name: pod-tfexecutor
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: backend
  name: backend
  namespace: kafkaml
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-backend
  template:
    metadata:
      labels:
        name: pod-backend
      name: backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      automountServiceAccountToken: true
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: brokers
              name: kafkaml-configmap
        - name: CONTROL_TOPIC
          valueFrom:
            configMapKeyRef:
              key: control.topic
              name: kafkaml-configmap
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TENSORFLOW_TRAINING_MODEL_IMAGE
          valueFrom:
            configMapKeyRef:
              key: tensorflow.training.image
              name: kafkaml-configmap
        - name: TENSORFLOW_INFERENCE_MODEL_IMAGE
          valueFrom:
            configMapKeyRef:
              key: tensorflow.inference.image
              name: kafkaml-configmap
        - name: PYTORCH_TRAINING_MODEL_IMAGE
          valueFrom:
            configMapKeyRef:
              key: pytorch.training.image
              name: kafkaml-configmap
        - name: PYTORCH_INFERENCE_MODEL_IMAGE
          valueFrom:
            configMapKeyRef:
              key: pytorch.inference.image
              name: kafkaml-configmap
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              key: frontend.url
              name: kafkaml-configmap
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              key: backend.url
              name: kafkaml-configmap
        - name: TFEXECUTOR_URL
          valueFrom:
            configMapKeyRef:
              key: tfexecutor.url
              name: kafkaml-configmap
        - name: PTHEXECUTOR_URL
          valueFrom:
            configMapKeyRef:
              key: pthexecutor.url
              name: kafkaml-configmap
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: backend.allowedhosts
              name: kafkaml-configmap
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: debug
              name: kafkaml-configmap
              optional: true
        - name: MODEL_LOGGER_TOPIC
          valueFrom:
            configMapKeyRef:
              key: federated.modelloggertopic
              name: kafkaml-configmap
              optional: true
        image: ertis/kafka-ml-backend:v1.0@sha256:9c95930a9b53c9bef03392820d5f9c41c8b51cbb185ccf5fc19da849c135ec1e
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8000
      serviceAccountName: kafkaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: kafkaml
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-frontend
  template:
    metadata:
      labels:
        name: pod-frontend
      name: frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - env:
        - name: BACKEND_PROXY_URL
          valueFrom:
            configMapKeyRef:
              key: backend.url
              name: kafkaml-configmap
        image: ertis/kafka-ml-frontend:v1.0@sha256:272d05517b63bb5209962b34ddc39d933729d7fdb876d0370c0c58df4357b72b
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kafka
  name: kafka
  namespace: kafkaml
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
      name: kafka
    spec:
      containers:
      - env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:9094,CONTROLLER://:9093
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_ENABLE_KRAFT
          value: "true"
        image: docker.io/bitnami/kafka:3.4.0-debian-11-r22
        imagePullPolicy: Always
        name: kafka
        ports:
        - containerPort: 9092
        - containerPort: 9094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kafka-control-logger
  name: kafka-control-logger
  namespace: kafkaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-control-logger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-control-logger
      name: kafka-control-logger
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: brokers
              name: kafkaml-configmap
        - name: CONTROL_TOPIC
          valueFrom:
            configMapKeyRef:
              key: control.topic
              name: kafkaml-configmap
        - name: BACKEND
          valueFrom:
            configMapKeyRef:
              key: backend.address
              name: kafkaml-configmap
        image: ertis/kafka-ml-kafka_control_logger:v1.0@sha256:64aa020e45ff68d90251fdaa097f73104d25e806ee8a56be6d978ba6011e91be
        imagePullPolicy: Always
        name: kafka-control-logger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pthexecutor
  name: pthexecutor
  namespace: kafkaml
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-pthexecutor
  template:
    metadata:
      labels:
        name: pod-pthexecutor
      name: pthexecutor
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: ertis/kafka-ml-pthexecutor:v1.0@sha256:4747e8bfb5d42bf6f201f1097932cfff45fcf165c6584e150ed79854c8ebb235
        imagePullPolicy: Always
        name: pthexecutor
        ports:
        - containerPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: tfexecutor
  name: tfexecutor
  namespace: kafkaml
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-tfexecutor
  template:
    metadata:
      labels:
        name: pod-tfexecutor
      name: tfexecutor
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: ertis/kafka-ml-tfexecutor:v1.0@sha256:5f6e5ba5c6bf74b75500c27c53388d3a792a45204ba2004e38976db774ee4a9d
        imagePullPolicy: Always
        name: tfexecutor
        ports:
        - containerPort: 8001
