apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka
  name: kafka
spec:
  ports:
  - name: "9094"
    port: 9094
    targetPort: 9094
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka
  type: LoadBalancer
status:
  loadBalancer: {}