resources:
  - "../base"

configMapGenerator:
  - name: kafkaml-configmap
    behavior: merge
    literals:
      - tensorflow.training.image=ertis/kafka-ml-tensorflow_model_training:master
      - tensorflow.inference.image=ertis/kafka-ml-tensorflow_model_inference:master
      - pytorch.training.image=ertis/kafka-ml-pytorch_model_training:master
      - pytorch.inference.image=ertis/kafka-ml-pytorch_model_inference:master

images:
  - name: kafka-ml-backend
    newName: ertis/kafka-ml-backend
    newTag: master
  - name: kafka-ml-frontend
    newName: ertis/kafka-ml-frontend
    newTag: master
  - name: kafka-ml-kafka_control_logger
    newName: ertis/kafka-ml-kafka_control_logger
    newTag: master
  - name: kafka-ml-pthexecutor
    newName: ertis/kafka-ml-pthexecutor
    newTag: master
  - name: kafka-ml-tfexecutor
    newName: ertis/kafka-ml-tfexecutor
    newTag: master
