on:
  push:
    paths:
      - mlcode_executor/pthexecutor/**/*
    branches:
      - "master"
      - "main"
      - "latest"
      - "dev*"
  release:
    types:
      - created
jobs:
  build-pthexecutor:
    strategy:
      matrix:
        include:
          - name: kafka-ml-pthexecutor
          - name: kafka-ml-pthexecutor-gpu
            build-args: "BASEIMG=pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime"
    uses: ./.github/workflows/build.yml
    with:
      context: mlcode_executor/pthexecutor
      dockerfile: mlcode_executor/pthexecutor/Dockerfile
      name: ${{ matrix.name }}
      platforms: linux/amd64
      build-args: ${{ matrix.build-args }}
    secrets: inherit
