on:
  push:
    paths:
      - model_inference/pytorch/**/*
    branches:
      - "master"
      - "main"
      - "latest"
      - "dev*"
  release:
    types:
      - created
jobs:
  build-pth-model-inference:
    strategy:
      matrix:
        include:
          - name: kafka-ml-pytorch_model_inference
          - name: kafka-ml-pytorch_model_inference-gpu
            build-args: "BASEIMG=pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime"
    uses: ./.github/workflows/build.yml
    with:
      context: model_inference/pytorch
      dockerfile: model_inference/pytorch/Dockerfile
      name: ${{ matrix.name }}
      platforms: linux/amd64
      build-args: ${{ matrix.build-args }}
    secrets: inherit
