on:
  push:
    paths:
      - model_inference/tensorflow/**/*
    branches:
      - "master"
      - "main"
      - "latest"
      - "dev*"
  release:
    types:
      - created
jobs:
  build-tf-model-inference:
    strategy:
      matrix:
        include:
          - name: kafka-ml-tensorflow_model_inference
          - name: kafka-ml-tensorflow_model_inference-gpu
            build-args: "TFTAG=2.15.0-gpu"
    uses: ./.github/workflows/build.yml
    with:
      context: model_inference/tensorflow
      dockerfile: model_inference/tensorflow/Dockerfile
      name: ${{ matrix.name }}
      platforms: linux/amd64
      build-args: ${{ matrix.build-args }}
    secrets: inherit
