on:
  push:
    paths:
      - mlcode_executor/tfexecutor/**/*
    branches:
      - "master"
      - "main"
      - "latest"
      - "dev*"
  release:
    types:
      - created
jobs:
  build-tfexecutor:
    strategy:
      matrix:
        include:
          - name: kafka-ml-tfexecutor
          - name: kafka-ml-tfexecutor-gpu
            build-args: "TFTAG=2.7.0-gpu"
    uses: ./.github/workflows/build.yml
    with:
      context: mlcode_executor/tfexecutor
      dockerfile: mlcode_executor/tfexecutor/Dockerfile
      name: ${{ matrix.name }}
      platforms: linux/amd64
      build-args: ${{ matrix.build-args }}
    secrets: inherit
